name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecutar todos los días a medianoche UTC
  workflow_dispatch:  # Permite ejecutar manualmente
  push:
    branches:
      - main  # Ejecutar cuando haya un push a la rama principal

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write  # Asegúrate de que el token tenga permisos de escritura

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Paso 2: Generar animaciones de GitHub Snake
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: Luishernan5  # Tu nombre de usuario en GitHub
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Paso 3: Desplegar los archivos generados a la rama 'output'
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output  # Aquí se publica en la rama 'output'
          commit_message: "Update snake animation [skip ci]"
